order_report_procedure		CREATE DEFINER=`lextech`@`%` PROCEDURE `order_report_procedure`()
BEGIN

DECLARE errorcode CHAR (5);
DECLARE msg TEXT;
DECLARE recordCount INT(11);

DROP TABLE IF EXISTS order_report;

CREATE TABLE order_report(
	OrderId INT(11) NOT NULL,
	OrderCreationDate VARCHAR(10),
    OrderCreationTime VARCHAR(256), 
	CustomerId INT(11),
	OrderStatus ENUM('NO DRYVERS IN RANGE','NO DRYVERS AVAILABLE','PICKUP SCHEDULED','PICKUP REQUESTED','PICKUP EN ROUTE','PICKUP ARRIVING','PICKUP NO SHOW','PICKUP CANCELED','PROCESSING','INVALID CREDIT CARD','CLEANING','READY','DELIVERY SCHEDULED','DELIVERY REQUESTED','DELIVERY EN ROUTE','DELIVERY ARRIVING','DELIVERY NO SHOW','DELIVERY CANCELED','DELIVERED','READY TO BILL','ORPHAN','READY_PMT_FAILED', 'PMT FAILED', 'RETRIEVED'),
	FirstName VARCHAR(256),
	LastName VARCHAR(256),
    Email VARCHAR(256),
    Address VARCHAR(256),
	Address2 VARCHAR(256),
	City VARCHAR(256),
	State VARCHAR(2),
	ZipCode VARCHAR(5),
	PostalCodeSuffix VARCHAR(10),
	Store VARCHAR(256),
	Region VARCHAR(256),
	CouponCodeUsed VARCHAR(256),
	Origin VARCHAR(256),
	SubscriptionOrder VARCHAR(1),
	RecurringOrder VARCHAR(1),
	Frequency VARCHAR(8),
	CustomerType VARCHAR(12),
	NonSubscriptionLaundryTrans DECIMAL(40, 2),
	LaundryByPoundTrans DECIMAL(40, 2),
	WashAndFoldTotes DECIMAL(27, 0),
	WashAndFoldPoundsSubscriber DECIMAL(26, 1),
    WashAndFoldPoundsOverflow DECIMAL(26, 1),
    WashAndFoldOverflowRevenue DECIMAL(37, 0),
	WashAndFoldRevenueNonSubscription DECIMAL(37, 0),
    WashAndFoldPoundsNonSubscription DECIMAL(26, 0),
    WashAndPressCounts DECIMAL(27, 0),
    DeliveredAmount DECIMAL(32, 0),
    ChargedAmount DECIMAL(32, 0),
    WashAndPressTotal DECIMAL(40, 2),
	DryCleanCounts DECIMAL(27, 0),
	DryCleanTotal DECIMAL(40, 2),
	HouseholdCounts DECIMAL(27, 0),
    HouseholdTotal DECIMAL(40, 2),
    CouponApplied DECIMAL(35, 2),
    DeliveryFee DECIMAL(35, 2),
    BaseSales DECIMAL(40, 2),
    ItemTotal DECIMAL(42, 2),
    CreditsUsed DECIMAL(36, 2),
    Tax DECIMAL(35, 2),
    GrandTotal DECIMAL(42, 2),
    Starch TINYINT(4),
    PantsCrease TINYINT(4),
	AdditionalDetails VARCHAR(255),
    PickupLocation ENUM('Front Door','Back Door','With the Doorman'),
    PickupDetails TEXT,
    SpecialInstructions VARCHAR(512),
    LocationType VARCHAR(11),
    ScheduledPickupDate VARCHAR(10),
    RequestedPickupDate VARCHAR(10),
    ActualPickupDate VARCHAR(10),
    ActualPickupTime TIME,
    ScheduledDeliveryDate VARCHAR(10),
    RequestedDeliveryDate VARCHAR(10),
    ActualDeliveryDate VARCHAR(10),
    ActualDeliveryTime TIME,
    DeliveryDriver TEXT,
    PickupDriver TEXT,
    PickupSkipped VARCHAR(1),
    SkippedBy VARCHAR(16),
    NumberOfStars TINYINT(1),
    Review VARCHAR(255)
);

/* insert new records into order_report */

INSERT INTO order_report
(OrderId,
	OrderCreationDate,
    OrderCreationTime, 
	CustomerId,
	OrderStatus,
	FirstName,
	LastName,
    Email,
    Address,
	Address2,
	City,
	State,
	ZipCode,
	PostalCodeSuffix,
	Store,
	Region,
	CouponCodeUsed,
	Origin,
	SubscriptionOrder,
	RecurringOrder,
	Frequency,
	CustomerType,
	NonSubscriptionLaundryTrans,
	LaundryByPoundTrans,
	WashAndFoldTotes,
	WashAndFoldPoundsSubscriber,
    WashAndFoldPoundsOverflow,
    WashAndFoldOverflowRevenue,
	WashAndFoldRevenueNonSubscription,
    WashAndFoldPoundsNonSubscription,
    WashAndPressCounts,
    DeliveredAmount,
    ChargedAmount,
    WashAndPressTotal,
	DryCleanCounts,
	DryCleanTotal,
	HouseholdCounts,
    HouseholdTotal,
    CouponApplied,
    DeliveryFee,
    BaseSales,
    ItemTotal,
    CreditsUsed,
    Tax,
    GrandTotal,
    Starch,
    PantsCrease,
	AdditionalDetails,
    PickupLocation,
    PickupDetails,
    SpecialInstructions,
    LocationType,
    ScheduledPickupDate,
    RequestedPickupDate,
    ActualPickupDate,
    ActualPickupTime,
    ScheduledDeliveryDate,
    RequestedDeliveryDate,
    ActualDeliveryDate,
    ActualDeliveryTime,
    DeliveryDriver,
    PickupDriver,
    PickupSkipped,
    SkippedBy,
    NumberOfStars,
    Review)
SELECT OrderId,
	DATE_FORMAT(STR_TO_DATE(OrderCreationDate, '%m/%d/%Y'), '%Y/%m/%d'),
    OrderCreationTime, 
	CustomerId,
	OrderStatus,
	FirstName,
	LastName,
    Email,
    Address,
	`Address 2`,
	City,
	State,
	Zip,
	PostalCodeSuffix,
	Store,
	Region,
	CouponCodeUsed,
	Origin,
	SubscriptionOrder,
	RecurringOrder,
	Frequency,
	CustomerType,
	NonSubscriptionLaundryTrans,
	LaundryByPoundTrans,
	WashandFoldTotes,
	WashandFoldPoundsSubscriber,
    WashandFoldPoundsOverflow,
    WashandFoldOverflowRevenue,
	WashandFoldRevenueNonSubscription,
    WashandFoldPoundsNonSubscription,
    WashandPressCounts,
	DeliveredAmount,
    ChargedAmount,
    WashandPressTotal,
	DryCleanCounts,
	DryCleanTotal,
	HouseholdCounts,
    HouseholdTotal,
    CouponApplied,
    DeliveryFee,
    BaseSales,
    ItemTotal,
    CreditsUsed,
    Tax,
    Grandtotal,
    Starch,
    PantsCrease,
	AdditionalDetails,
    PickupLocation,
    PickupDetails,
    SpecialInstructions,
    LocationType,
    DATE_FORMAT(STR_TO_DATE(ScheduledPickupDate, '%m/%d/%Y'), '%Y/%m/%d'),
    DATE_FORMAT(STR_TO_DATE(RequestedPickupDate, '%m/%d/%Y'), '%Y/%m/%d'),
    DATE_FORMAT(STR_TO_DATE(ActualPickupDate, '%m/%d/%Y'), '%Y/%m/%d'),
    ActualPickupTime,
	DATE_FORMAT(STR_TO_DATE(ScheduledDeliveryDate, '%m/%d/%Y'), '%Y/%m/%d'),
	DATE_FORMAT(STR_TO_DATE(RequestedDeliveryDate, '%m/%d/%Y'), '%Y/%m/%d'),
	DATE_FORMAT(STR_TO_DATE(ActualDeliveryDate, '%m/%d/%Y'), '%Y/%m/%d'),
    ActualDeliveryTime,
    DeliveryDriver,
    PickupDriver,
    PickupSkipped,
    SkippedBy,
    NumberOfStars,
    Review
    FROM v_OrderReport;
    
SELECT 0;

END	utf8mb4	utf8mb4_general_ci	latin1_swedish_ci
