customer_report_procedure		CREATE DEFINER=`lextech`@`%` PROCEDURE `customer_report_procedure`()
BEGIN


DECLARE errorcode CHAR (5);
DECLARE msg TEXT;
DECLARE recordCount INT(11);

DROP TABLE IF EXISTS customer_report;

SET SESSION optimizer_switch='block_nested_loop=off';

CREATE TABLE customer_report(
CustomerId VARCHAR(11) ,
	NewCustomer VARCHAR(1),
    FirstName VARCHAR(256),
	LastName VARCHAR(256),
	EmailAddress VARCHAR(256),
	PhoneNumber VARCHAR(256),
	UserReferralCode VARCHAR(256),
    Address VARCHAR(256),
	Address2 VARCHAR(256),
	City VARCHAR(256),
	State VARCHAR(2),
	ZipCode VARCHAR(5),
	ZipCode4Code VARCHAR(10),
	Store VARCHAR(256),
	Territory VARCHAR(256),
	CurrentCustomerType VARCHAR(12),
	Frequency VARCHAR(32),
	SubscriptionOptInDate VARCHAR(10),
	InTerritory VARCHAR(1),
	SubscriptionOptOutDate VARCHAR(10),
	FirstOrderCouponCode VARCHAR(255),
	FirstOrderType VARCHAR(12),
    TotalOfPromoCodes VARCHAR(21),
	RegistrationDate VARCHAR(10),
	RegistrationTime TIME,
	FirstOrderDate VARCHAR(10),
	FirstOrderTime TIME,
	LastOrderDate VARCHAR(10),
	LastOrderTime TIME,
    FirstOrderSubmittedDate VARCHAR(10),
	TotalNumberOfOrders BIGINT(21),
	requested_ready_date VARCHAR(10),
	FirstOrderSubmittedTime TIME,
    SubscriptionOrder VARCHAR(1),
    RecurringOrder VARCHAR(32),
    UsedDryCleaning VARCHAR(1),
    TotalNumberOfBags DECIMAL(49, 0),
    SubscribedBags INT(11),
    TotalSkippedOrders BIGINT(21),
    TotalOrderSpend DECIMAL(64, 2),
    CreditsRemaining DOUBLE(19, 2),
    CustomerOrders BIGINT(21),
	Referred BIGINT(21),
    TotalSubscriptionSpend DECIMAL(35, 2),
    TotalRefunds DECIMAL(35, 2)
    );
INSERT INTO customer_report(
CustomerId,
	NewCustomer,
    FirstName,
	LastName,
	EmailAddress,
	PhoneNumber,
	UserReferralCode,
    Address,
	Address2,
	City,
	State,
	ZipCode,
	ZipCode4Code,
	Store,
	Territory,
	CurrentCustomerType,
	Frequency,
	SubscriptionOptInDate,
	InTerritory,
	SubscriptionOptOutDate,
	FirstOrderCouponCode,
	FirstOrderType,
    TotalOfPromoCodes,
	RegistrationDate,
	RegistrationTime,
	FirstOrderDate ,
	FirstOrderTime,
	LastOrderDate,
	LastOrderTime,
    FirstOrderSubmittedDate,
	TotalNumberOfOrders,
	requested_ready_date,
	FirstOrderSubmittedTime,
    SubscriptionOrder,
    RecurringOrder,
    UsedDryCleaning,
    TotalNumberOfBags,
    SubscribedBags,
    TotalSkippedOrders,
    TotalOrderSpend,
    CreditsRemaining,
    CustomerOrders,
	Referred,
    TotalSubscriptionSpend,
    TotalRefunds
)
SELECT CustomerId,
	NewCustomer,
    FirstName,
	LastName,
	EmailAddress,
	PhoneNumber,
	UserReferralCode,
    Address,
	Address2,
	City,
	State,
	ZipCode,
	ZipPlus4Code,
	Store,
	Territory,
	CurrentCustomerType,
	Frequency,
    DATE_FORMAT(STR_TO_DATE(SubscriptionOptInDate, '%m/%d/%Y'), '%Y/%m/%d'),
	InTerritory,
    DATE_FORMAT(STR_TO_DATE(SubscriptionOptOutDate, '%m/%d/%Y'), '%Y/%m/%d'),
	FirstOrderCouponCode,
	FirstOrderType,
    TotalOfPromoCodes,
    DATE_FORMAT(STR_TO_DATE(RegistrationDate, '%m/%d/%Y'), '%Y/%m/%d'),
	RegistrationTime,
     DATE_FORMAT(STR_TO_DATE(FirstOrderDate, '%m/%d/%Y'), '%Y/%m/%d'),
	FirstOrderTime,
    DATE_FORMAT(STR_TO_DATE(LastOrderDate, '%m/%d/%Y'), '%Y/%m/%d'),
	LastOrderTime,
    DATE_FORMAT(STR_TO_DATE(FirstOrderSubmittedDate, '%m/%d/%Y'), '%Y/%m/%d'),
	TotalNumberOfOrders,
	DATE_FORMAT(STR_TO_DATE(requested_ready_date, '%m/%d/%Y'), '%Y/%m/%d'),
	FirstOrderSubmittedTime,
    SubscriptionOrder,
    RecurringOrder,
    UsedDryCleaning,
    TotalNumberOfBags,
    SubscribedBags,
    TotalSkippedOrders,
    TotalOrderSpend,
    CreditsRemaining,
    CustomerOrders,
	Referred,
    TotalSubscriptionSpend,
    TotalRefunds
FROM v_CustomerReport
ORDER BY CustomerId;

SELECT 0;

END	utf8	utf8_general_ci	latin1_swedish_ci
